name: CI/CD Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Test DATABASE_URL
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "❌ DATABASE_URL n'est pas défini"
            exit 1
          else
            echo "✅ DATABASE_URL est correctement configuré"
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install dependencies
        run: cd virtuo-piano && npm install

      - name: Build
        run: cd virtuo-piano && npm run vercel-build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
