name: manualTrigger

on:
  workflow_dispatch:

jobs:
  Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "My Database URL is ${{ secrets.DATABASE_URL }}"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd virtuo-piano && npm install

      - name: Build
        run: cd virtuo-piano && npm run vercel-build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
