name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  test-unitaires:
    name: Tests Unitaires
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "virtuo-piano/package-lock.json"

      - name: Install dependencies
        run: cd virtuo-piano && npm install

      - name: Run unit tests
        run: cd virtuo-piano && npm run test:unit

  test-integration:
    name: Tests d'Intégration
    runs-on: ubuntu-latest
    needs: test-unitaires
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "virtuo-piano/package-lock.json"

      - name: Install dependencies
        run: cd virtuo-piano && npm install

      - name: Run integration tests
        run: cd virtuo-piano && npm run test:integration

  test-components:
    name: Tests de Composants
    runs-on: ubuntu-latest
    needs: test-unitaires
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "virtuo-piano/package-lock.json"

      - name: Install dependencies
        run: cd virtuo-piano && npm install

      - name: Run component tests
        run: cd virtuo-piano && npm run test:components

  test-e2e:
    name: Tests E2E
    runs-on: ubuntu-latest
    needs: [test-components, test-integration]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "virtuo-piano/package-lock.json"

      - name: Install dependencies
        run: cd virtuo-piano && npm install

      - name: Run E2E tests
        run: cd virtuo-piano && npm run test:e2e

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test-unitaires, test-integration, test-components, test-e2e]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "virtuo-piano/package-lock.json"

      - name: Install dependencies
        run: cd virtuo-piano && npm install

      - name: Build
        run: cd virtuo-piano && npm run vercel-build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
